##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - aptitude
    - build-essential
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - git
    - docbook-xml
    - gettext
    - gobject-introspection
    - gtk-doc-tools
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgtk-3-dev
    - libgtk-3-doc
    - libstartup-notification0-dev
    - libx11-dev
    - libxext-dev
    - libxres-dev
    - meson
    - ninja-build

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0'

build_scripts:
  - ./before-build
  - ./make-scanbuild meson
  - ./after-build

after_scripts:
  - ./gen-index -l 20
